// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0d2GVQuy-eHB0LO58MK3GieQpdoUkAXQ',
    appId: '1:743771809067:web:9cf8d371d353b61735516e',
    messagingSenderId: '743771809067',
    projectId: 'questionfl',
    authDomain: 'questionfl.firebaseapp.com',
    storageBucket: 'questionfl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPpGsaBD2_noAyncPayyCJ62bfiN_6aPo',
    appId: '1:743771809067:android:363be6e0115211b435516e',
    messagingSenderId: '743771809067',
    projectId: 'questionfl',
    storageBucket: 'questionfl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIC0wBJ8n0IBrplqR-znvPUPBBXywXxOE',
    appId: '1:743771809067:ios:8e1d71396e93db6f35516e',
    messagingSenderId: '743771809067',
    projectId: 'questionfl',
    storageBucket: 'questionfl.appspot.com',
    iosClientId: '743771809067-e2tumpbp7pcqo9lb1d26a1h6a656lsgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.questionabout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIC0wBJ8n0IBrplqR-znvPUPBBXywXxOE',
    appId: '1:743771809067:ios:c9134dfda85a1fe135516e',
    messagingSenderId: '743771809067',
    projectId: 'questionfl',
    storageBucket: 'questionfl.appspot.com',
    iosClientId: '743771809067-26a240otkf7leja18i51hfhmvs7pf7at.apps.googleusercontent.com',
    iosBundleId: 'com.example.questionabout.RunnerTests',
  );
}
